### ISSUE TITLE
Segmentation fault on certain computers

### ISSUE THREAD

**Issue by wilkojohnny** [ISISMuon/MuonDataLib#36]
When trying to split a long run into a series of short runs using the attached script (change .txt to .py), HiFi run 194372 results in a 'Segmentation error' after successfully filtering and saving a number of runs.
[TimeSlice1.txt](https://github.com/user-attachments/files/18200371/TimeSlice1.txt)

This is only reproducable on some machines working on some enviroments: 
- Windows 10 running python 3.11, obtained from python directly
- Mac OS Somona running python 3.11 [from homebrew]
- IDAaaS instances when using python 3.11 in PATH

We have not been able to reproduce the problem on the following:
- Windows 10/11 running python 3.11 obtained from MS store
- IDAaaS instances using Jupyter notebooks

The attached file SegmentationError.txt shows the error log from my Mac machine, which suggests it is in the function good_values_ints(..) in filter.pyx. If we turn on the cython bounds checking, we get the following traceback:
Traceback (most recent call last):
  File "/Users/john.wilkinson/scratch/TimeSlice1.py", line 71, in <module>
    data.save_histograms(output_file)
  File "/Users/john.wilkinson/scratch/MuonDataLib/src/MuonDataLib/data/muon_data.py", line 67, in save_histograms
    self._events.histogram(cache=self._cache)
  File "src/MuonDataLib/cython_ext/event_data.pyx", line 165, in MuonDataLib.cython_ext.event_data.Events.histogram
  File "src/MuonDataLib/cython_ext/filter.pyx", line 121, in MuonDataLib.cython_ext.filter.good_values_ints
  File "src/MuonDataLib/cython_ext/filter.pyx", line 144, in MuonDataLib.cython_ext.filter.good_values_ints
IndexError: Out of bounds on buffer access (axis 0)

[SegmentationError.txt](https://github.com/user-attachments/files/18200428/SegmentationError.txt)

**Comment by AnthonyLim23** [comment]
This is an interesting error. Looking at the code, https://github.com/ISISMuon/MuonDataLib/blob/main/src/MuonDataLib/cython_ext/filter.pyx#L144, the problem is that the number of filter end points is less than the number of filter start points. This is a very odd error, which should not occur.

@wilkojohnny what filters were being used when this error occurred?

**Comment by AnthonyLim23** [comment]
add check for time array is in correct order (i.e. cf with sort)

**Comment by AnthonyLim23** [comment]
if it fails, throw an error. Will have a separate script to fix the order

**Comment by AnthonyLim23** [comment]
use a binary search. 

If we have N frames then a binary search scales as log(N).

We want to know when

N = alpha log(N)

where alpha is a number of binary searches. 

alpha = N / log(N)

However, for each filter we have 2 searches (start and end). Hence, the number of filters M is

M = 2 alpha
Hence, 
M = 2N / log(N)

we want to make sure that doing a binary search is more efficient than just checking every frame manually. 

If the manual search is more efficient then

N > M = 2N/log(N)

log(N) > 2

N > 10^2 = 100

So it is better to do a binary search if there are more than 100 frames. This is probably a safe assumption
